@baseURL = https://api.iextrading.com/1.0/stock/market
@symbols = MSFT,GOOG,FB,AMZN
@types = peers,news,quote,chart
@collection = {{baseURL}}/collection
@sector = sector-performance
@contentType = application/json
@duration = 1m
@stories = 5

#

### Get Batch
GET {{baseURL}}/batch
?symbols={{symbols}}
&types={{types}}
&range={{duration}}
&last={{stories}}
Accept-Encoding: {{contentType}}

### Sector Performance
GET {{baseURL}}/{{sector}} HTTP/1.1
Accept-Encoding: {{contentType}}

### Gainers
GET {{baseURL}}/list/gainers HTTP/1.1
Accept-Encoding: {{contentType}}

### Losers
GET {{baseURL}}/list/losers HTTP/1.1
Accept-Encoding: {{contentType}}

### Most Active
GET {{baseURL}}/list/mostactive HTTP/1.1
Accept-Encoding: {{contentType}}

### In Focus
GET {{baseURL}}/list/infocus HTTP/1.1
Accept-Encoding: {{contentType}}
