let
    Source = Excel.CurrentWorkbook(){[Name="Patrick"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"DIV", type text}, {"DIV NO", Int64.Type}, {"PROD", type text}, {"UNIT", type text}, {"SIZE", type text}, {"BRAND", type text}, {"DESCRIPTION", type text}, {"MANUF #", type any}, {"EXT DESC", type text}, {"CURRENT FOB", type number}, {"OTHER", Int64.Type}, {"CURR LANDED", type number}, {"CURR MARKET", type number}, {"PROP ID", type any}, {"PROP NAME", type text}, {"RESTRICTED", type text}, {"BUYER", Int64.Type}, {"BUYER NAME", type text}, {"ON HAND", Int64.Type}, {"SLOT", type text}, {"CURR UNITS", Int64.Type}, {"WK 1 UNITS", Int64.Type}, {"WK 2 UNITS", Int64.Type}, {"YTD UNITS", Int64.Type}, {"VENDOR #", Int64.Type}, {"VEND NAME", type text}, {"CUTOFF", type any}, {"E3 FLAG", type text}, {"ON ORDER", Int64.Type}, {"AVG MOVE", type number}, {"EOQ FLAG", type text}, {"BROKER", type any}, {"VEND PHONE", Int64.Type}, {"BRK PHONE", type any}, {"VEND BUYER", Int64.Type}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"DIV", "DIV NO", "MANUF #", "BROKER", "VEND PHONE", "BRK PHONE", "VEND BUYER", "CUTOFF"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"PROD", "VEND NAME", "VENDOR #", "UNIT", "SIZE", "BRAND", "DESCRIPTION", "EXT DESC", "CURRENT FOB", "OTHER", "CURR LANDED", "CURR MARKET", "PROP ID", "PROP NAME", "RESTRICTED", "BUYER", "BUYER NAME", "ON HAND", "SLOT", "CURR UNITS", "WK 1 UNITS", "WK 2 UNITS", "YTD UNITS", "E3 FLAG", "ON ORDER", "AVG MOVE", "EOQ FLAG"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns",{"OTHER"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns1",{"PROD", "VEND NAME", "VENDOR #", "UNIT", "SIZE", "BRAND", "DESCRIPTION", "EXT DESC", "PROP ID", "PROP NAME", "CURRENT FOB", "CURR LANDED", "CURR MARKET", "RESTRICTED", "BUYER", "BUYER NAME", "ON HAND", "SLOT", "CURR UNITS", "WK 1 UNITS", "WK 2 UNITS", "YTD UNITS", "E3 FLAG", "ON ORDER", "AVG MOVE", "EOQ FLAG"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Reordered Columns1",{{"PROP ID", type text}}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Changed Type1",{"PROD", "VEND NAME", "VENDOR #", "UNIT", "SIZE", "BRAND", "DESCRIPTION", "EXT DESC", "PROP ID", "PROP NAME", "RESTRICTED", "CURRENT FOB", "CURR LANDED", "CURR MARKET", "BUYER", "BUYER NAME", "ON HAND", "SLOT", "CURR UNITS", "WK 1 UNITS", "WK 2 UNITS", "YTD UNITS", "E3 FLAG", "ON ORDER", "AVG MOVE", "EOQ FLAG"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns2",{"BUYER", "BUYER NAME"}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Removed Columns2",{"PROD", "VEND NAME", "VENDOR #", "UNIT", "SIZE", "BRAND", "DESCRIPTION", "EXT DESC", "PROP ID", "PROP NAME", "RESTRICTED", "EOQ FLAG", "E3 FLAG", "SLOT", "CURRENT FOB", "CURR LANDED", "CURR MARKET", "ON HAND", "ON ORDER", "AVG MOVE", "CURR UNITS", "WK 1 UNITS", "WK 2 UNITS", "YTD UNITS"}),
    #"Capitalized Each Word" = Table.TransformColumns(#"Reordered Columns3",{{"VEND NAME", Text.Proper, type text}, {"DESCRIPTION", Text.Proper, type text}, {"EXT DESC", Text.Proper, type text}, {"BRAND", Text.Proper, type text}, {"PROP NAME", Text.Proper, type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Capitalized Each Word","*","",Replacer.ReplaceText,{"VEND NAME", "BRAND", "DESCRIPTION", "EXT DESC", "PROP NAME"}),
    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"PROD", "Prod #"}, {"VEND NAME", "Vendor"}, {"VENDOR #", "Vend #"}, {"UNIT", "Unit"}, {"SIZE", "Size"}, {"BRAND", "Brand"}, {"DESCRIPTION", "Desc."}, {"EXT DESC", "Desc.2"}, {"PROP ID", "PC"}, {"PROP NAME", "Prop"}, {"RESTRICTED", "Restr."}, {"EOQ FLAG", "EOQ"}, {"E3 FLAG", "E3"}, {"SLOT", "Slot"}, {"CURRENT FOB", "FOB"}, {"CURR LANDED", "Landed"}, {"CURR MARKET", "Market"}, {"ON HAND", "OH"}, {"ON ORDER", "OO"}, {"AVG MOVE", "Avg"}, {"CURR UNITS", "W0"}, {"WK 1 UNITS", "W1"}, {"WK 2 UNITS", "W2"}, {"YTD UNITS", "TYD"}})
in
    #"Renamed Columns"